guests = ['Mrs Youth', 'Mrs Kufre', 'Mrs Esther', 'Mr Essien']
print("\t'Hi' + ' ' + guests[0] + 'please join me and my family tonight for dinner @ 9pm\n see you soon'")
print('Hi' + ' ' + guests[1] + 'please join me and my family tonight for dinner @ 9pm\n see you soon')
print('Hi' + ' ' + guests[2] + 'please join me and my family tonight for dinner @ 9pm\n see you soon')
print('Hi' + ' ' + guests[3] + 'please join me and my family tonight for dinner @ 9pm\n see you soon')
print(guests[0] + ' ' + 'says she won\'t make it tonight')
guests.insert(0,'Alice')
print(guests)
del guests[1]
print(guests)
print('Hi' + ' ' + guests[0] + ' ' + 'please join me and my family tonight for dinner @ 9pm\n see you soon')
print('I found a bigger dinning table guys')
guests.insert(0,'Itoro')
print(guests)
guests.insert(3,'Abas')
print(guests)
guests.append('Saviour')
print(guests)
print('Hi' + ' ' + guests[0] + 'please join me and my family tonight for dinner @ 9pm\n see you soon')
print('Hi' + ' ' + guests[1] + 'please join me and my family tonight for dinner @ 9pm\n see you soon')
print('Hi' + ' ' + guests[2] + 'please join me and my family tonight for dinner @ 9pm\n see you soon')
print('Hi' + ' ' + guests[3] + 'please join me and my family tonight for dinner @ 9pm\n see you soon')
print('Hi' + ' ' + guests[4] + 'please join me and my family tonight for dinner @ 9pm\n see you soon')
print('Hi' + ' ' + guests[5] + 'please join me and my family tonight for dinner @ 9pm\n see you soon')
print('Sorry guys, only 2 tables available')
guests.pop()
print(guests)
guests.pop()
print(guests)
guests.pop()
print(guests)
guests.pop()
print(guests)
guests.pop()
print(guests)
print('Hi' + ' ' + guests[0] + 'please join me and my family tonight for dinner @ 9pm\n see you soon')
print('Hi' + ' ' + guests[1] + 'please join me and my family tonight for dinner @ 9pm\n see you soon')
print(len(guests))
